### ISSUE TITLE
What products do this tools work with?

### ISSUE THREAD

**Issue by vrx-** [fraymio/modis-tools#18]
Hi, I was wondering if there are some MODIS products where this implementation doesn't work. Specifically, I was trying to use this to get level 1b Aqua data, but I get an empty collection. I do not know what the version attribute means, so that might be the issue.

```
username = "*****"  # Update this line
password = "****"  # Update this line
​
session = ModisSession(username=username, password=password)

collection_client = CollectionApi(session=session)
collections = collection_client.query(short_name="MYD021KM")
```
```
collections
[]
```

**Comment by jamie-sgro** [comment]
Hi @vrx- thanks for bringing this to our attention.
Try adding `version="006"` as a parameter to `collection_client.query`. 

I've just ran the same and it looks like it's a difference between the release version on PyPi and our current main branch. Since the decision to make `version` an optional parameter was made only just recently. I'll create a new issue to push a new release to PyPi given this.


![image](https://user-images.githubusercontent.com/78166093/179836454-d876ed96-d3a3-4f64-877b-ef32c1f65f2c.png)
