### ISSUE TITLE
No matching link found

### ISSUE THREAD

**Issue by MohammadJavadSoltani** [fraymio/modis-tools#30]
Dear MODIS Tools Provider team,

I hope you are doing well. I wanted to express my sincere appreciation for the fantastic MODIS-Tools library you've created. It has been invaluable in my research, particularly for collections like MOD021KM - V:6.1 and MOD03 - V:6.1.

However, I've encountered an issue with the following datasets:
VNP46A1 - V:1
VNP03DNB - V:1,2
VNP02DNB - V:1,2
VNP09A1 - V:001

Whenever I try to query these datasets, I consistently receive the error "Exception: No matching link found," even after trying multiple start and end dates.
I wonder if there are specific requirements or considerations for these datasets that I might have overlooked.

Any guidance you can provide to resolve this matter would be highly appreciated. Thank you for your excellent work on the MODIS-Tools library, which has significantly enhanced my research capabilities.

Best regards,
[MohammadJavad Soltani]

**Comment by cearlefraym** [comment]
Hi Mohammad, thanks for the note! We're glad you're getting some good use out of the tool. 

The reason you're getting this error is because the query is returning files with extensions other than `hdf` which is currently the only supported file extension. We're still looking into adding support for alternative formats, so I can suggest an **un-official** fix for now that requires changing one line of code. 

For the products you mentioned, `VNP46A1 - V:1` and ` VNP09A1 - V:001` are a collection of `h5` files, not `hdf`. If you are comfortable, you can clone the repo and change this line of code on your end:
https://github.com/fraymio/modis-tools/blob/main/modis_tools/granule_handler.py#L55 

There's a string there for `hdf` that can just be changed to `h5` to allow `VNP46A1` and `VNP09A1` to download. 

You should be able to get those products then: 
![image](https://github.com/fraymio/modis-tools/assets/97044512/3ac42986-3eed-4561-afa4-679b8306cc2e)

For the other two products `VNP03DNB - V:1,2` and ` VNP02DNB - V:1,2` these contain a collection of `pdf`, `html`, and `nc` so the `h5` swap won't work for these, but the same logic applies if you wanted to force these to download. Alternatively, you could deactivate the file extension check all together here https://github.com/fraymio/modis-tools/blob/main/modis_tools/granule_handler.py#L106

Again, these are unofficial hacks to get this to work for these specific products. We will continue to look into supporting additional file formats in the future, but I hope this can get you where you need to go in the short term.

**Comment by MohammadJavadSoltani** [comment]
I sincerely appreciate your gratitude and value the time you've taken to interact with me.
